version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.2.2
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://34.170.157.210:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - kafka-network

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: burak
      POSTGRES_PASSWORD: Burak115
      POSTGRES_DB: sevenapps
    ports:
      - "5432:5432"
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "burak", "-d", "sevenapps"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  kafka-network:
    driver: bridge
