apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
  namespace: sevenapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-service
  template:
    metadata:
      labels:
        app: metadata-service
    spec:
      containers:
        - name: metadata-service
          image: burakblm/metadata-extraction-service:latest
          envFrom:
            - configMapRef:
                name: metadata-service-config
          ports:
            - containerPort: 8002
