apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: sevenapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: burakblm/chat-service:latest
          envFrom:
            - configMapRef:
                name: chat-service-config
          ports:
            - containerPort: 8001
