name: Fetch and Print Secret

on:
  push:
    branches:
      - main

jobs:
  fetch-secret:
    runs-on: ubuntu-latest

    steps:
      # Google Cloud credentials'ı ayarlıyoruz
      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > "${HOME}/gcloud-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcloud-key.json"
      
      # Secret Manager'dan 'postgres-user' secret'ını alıyoruz
      - name: Fetch postgres-user secret
        run: |
          POSTGRES_USER=$(gcloud secrets versions access latest --secret="postgres-user")
          echo "Postgres User: $POSTGRES_USER"
