name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_HOST }} >> ~/.ssh/known_hosts

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: SSH into GCP VM and deploy
        env:
          HOST: ${{ secrets.GCP_VM_HOST }}
          USER: ${{ secrets.GCP_VM_USERNAME }}
        run: |
            ssh $USER@$HOST <<EOF
        
            cd /home/${USER}
                
            if [ -d "sevenapps-backend-task" ]; then
              cd sevenapps-backend-task
              git pull origin main
            else
              git clone https://github.com/Burakblm/sevenapps-backend-task.git
              cd sevenapps-backend-task
            fi
        
            
            cp /home/$USER/credentials.json upload/app/services/credentials.json
            cp /home/$USER/credentials.json metadata-extraction/app/services/credentials.json

            sudo docker-compose -f docker-compose-prod.yml down -v
            sudo docker-compose -f docker-compose-prod.yml up --build -d
        
            EOF